### ISSUE TITLE
Add a loop 

### ISSUE THREAD

**Issue by Asqit** [Magrid0/SimpleCalculator#1]
It's only my suggestion, but maybe you can add a loop of some sort into the program, so that the program don't quit after the first calculation. I am learning java from a MOOC course and almost in every exercise they have a loop, which ends when user enters a specific character.

e.g.

```java
...
while(true) {
   System.out.print("Do you wanna continue? (yes/no)");
   String feed = scanner.nextLine().toUpperCase();
   
   // short-circuit the app if empty line
   if (feed.equals("NO")) {
    break;
   }
  
   ...rest of your algorithm
}
```

**Comment by Magrid0** [comment]
i'll add it in the next version! (2.1).
It will probably be done by today.

**Comment by Magrid0** [comment]
[Done](https://github.com/Magrid0/SimpleCalculator/releases/tag/2.1).
