### ISSUE TITLE
Suggestion to share values between classes

### ISSUE THREAD

**Issue by DoNotWorr** [Magrid0/SimpleCalculator#2]
You use a class `GlobalVariables` to share variables from `SimpleCalculator` to `Calculator`.
I suggest you use methods with parameters instead.

Method signature:
```
public static void sum(int term1, int term2) {
    int sum = term1 + term2;
    System.out.println("\nThe result is: " + sum);
}
```

When collecting input:
```
// Enter the first number.
System.out.print("\nEnter the first number: ");
int firstNumber = Integer.parseInt(scanner.nextLine());

// Enter the second number.
System.out.print("\nEnter the second number (insert 0 for square root): ");
int secondNumber = Integer.parseInt(scanner.nextLine());
```

Later in the switch statement:
```
case 1 -> Calculator.sum(firstNumber, secondNumber);
```

The benefit of using variables with a local scope is that you won't have to worry about breaking your code by accidentally changing a variable somewhere else in your code base. For example `term1` would exist inside of the sum method.

**Comment by DoNotWorr** [comment]
**I also suggest you rewrite your Calculator methods return values.**

Your Calculator currently does two things: calculations _and_ printing to console.
```
public static void sum(int term1, int term2) {
    int sum = term1 + term2;
    System.out.println("\nThe result is: " + sum);
}
```
Two things is not a lot, but now you're committed to always doing two things in every method that you add to the Calculator class. Look how many times this line is repeated: `System.out.println("\nThe result is: " + `

Let's imagine all your methods looked like this instead:
```
public static int sum(int term1, int term2) {
    int sum = term1 + term2;
    return sum;
}
```

Then you can call the appropriate Calculator method and assign the return value to a variable and then print whatever was assigned to that variable

```
//declare variable
int result;

//assign value to variable
result = sum(firstNumber, secondNumber);

//print result
System.out.println("\nThe result is: " + result);
```

**Comment by Magrid0** [comment]
thank you so much for your suggestion.
I'll try to implement it in the next version!
